name: FreshmanPlugin
version: 1.0
main: tb.personal.FreshmanPlugin.FreshmanPlugin
api-version: 1.13
commands:
  Wizard:
    description: command for WIZARD settings including enabling recipes.
    usage: /Wizard [add/remove] [wand namespace/all]
    permission: op
